### ISSUE TITLE
Stream mp3 with mp3.js = UnderflowError

### ISSUE THREAD

**Issue by rtherry** [fabslab/aurora-websocket#1]
Hello, thx for your work :-)
I'd like to use your project to stream some music over websocket with aurora.js but i get an error. 
Whith your flac exmple, it works well. 
But when I try with your server exemple and an mp3 file, i get an UnderflowError. 
Do you know how i can fix this ? 
Thx

**Comment by fabslab** [comment]
Does your mp3 file work with aurora.js when not using my module?

**Comment by Pheo-Player** [comment]
Contrary to what I thought, using a different library for stream throttling does not fix this specific issue. I too get an UnderflowError for an MP3 file. And yes, it plays fine when I just serve it as a static file and use `AV.Player.fromUrl` instead.

**Comment by Pheo-Player** [comment]
This seems to be related to mp3.js itself, which seems to assume it has the whole stream loaded already at probing time. Opening an issue in that repo.

**Comment by fabslab** [comment]
Thanks @Pheo-Player, I guess it isn't worth changing the server example to use the other throttling library anymore?

**Comment by Pheo-Player** [comment]
I think it still is? We hopefully can figure this one out over in mp3.js :)

**Comment by Pheo-Player** [comment]
(and you most likely don't want to use a library that makes your node process hit 100% CPU in any example!)

**Comment by fabslab** [comment]
Okay, cool. I was checking since you said you were wrong about it fixing everything.

**Comment by rtherry** [comment]
Thx I'll try it soon.

**Comment by Pheo-Player** [comment]
I'm afraid it's likely not going to work, you might want to read the linked issues :)

**Comment by UCIS** [comment]
mp3.js does not need the entire file to be available, it just needs one complete frame and the header for the next frame. You can decode the MP3 stream to find the exact amount of data for the first two frames, or just send the first 10kB (or so) of data in one websocket frame. Both approaches worked for me.
