### ISSUE TITLE
Live Streaming with Aurora WS

### ISSUE THREAD

**Issue by sassyn** [fabslab/aurora-websocket#6]
Hi,

I have used your code to enable mp3 live streaming using FFMPEG
It is working as well as using AAC.

However, PCM seems to fail as well as any other format I was trying to use under IOS Safari.

Do you know maybe how to overcome this issue?

Thank You

**Comment by sassyn** [comment]
Any comments?

**Comment by fabslab** [comment]
For decoding issues you'll want to go to the main library Aurora. This plugin implements only the WebSocket transport.
